"""
Nexus Legacy — Discord Summary
Reads nexus-map-clean.json (generated by nl_dumper.py) and outputs
formatted system reports for posting in Discord.

Usage:
    python nl_discord_summary.py nldb.json --arm epsilon --sector 47
    python nl_discord_summary.py nldb.json --pvp --arm epsilon
    python nl_discord_summary.py nldb.json --type terra --min-slots 18
    python nl_discord_summary.py nldb.json --alliance NAV
    python nl_discord_summary.py nldb.json --alliance SWORD --pvp
    python nl_discord_summary.py nldb.json --player Khazrihl
    python nl_discord_summary.py nldb.json --unaffiliated --pvp
    python nl_discord_summary.py nldb.json --field-type ore --min-richness 2.0
    python nl_discord_summary.py nldb.json --sort-slots --top 50
    python nl_discord_summary.py nldb.json --list-alliances

Flags:
    --arm epsilon         filter by arm name (alpha/beta/gamma/delta/epsilon/zeta)
    --sector 47           filter to in-game sector number (requires --arm)
    --type terra          planet type: terra/gas_giant/rocky/ice/volcanic/crystalline
    --zone open           security zone: open/sentinel/dead/rift
    --pvp                 PvP zones only (open/dead/rift — excludes sentinel)
    --min-slots 10        minimum planet building slots (default 0)
    --colonized           systems with at least one colonized planet
    --unaffiliated        systems with a colony owned by a player with no alliance tag
    --alliance NAV        systems with a colony owned by this alliance tag
    --player Khazrihl     systems with a colony owned by this player (partial match)
    --list-alliances      print all alliance tags sorted by colony count, then exit
    --field-type ore      asteroid field type: ore/ice/gas/dark/plasma/quantum
    --min-richness 1.5    minimum asteroid field richness (default 0.0)
    --sort-slots          sort by highest planet slot count descending
    --top 25              max systems to show (default 25)
"""

import json, sys, argparse, re
from collections import defaultdict, Counter
from datetime import datetime

# ── Constants ─────────────────────────────────────────────────────────────────
ARM_LETTERS = {
    'A': 'Alpha', 'B': 'Beta',    'G': 'Gamma',
    'D': 'Delta', 'E': 'Epsilon', 'Z': 'Zeta',
}
ARM_NAMES_LOWER = {v.lower(): k for k, v in ARM_LETTERS.items()}

PLANET_EMOJI = {
    'terra':       '🟢',
    'rocky':       '🟤',
    'gas_giant':   '🟡',
    'ice':         '🔵',
    'volcanic':    '🔴',
    'crystalline': '💎',
}
ZONE_EMOJI = {
    'sentinel': '🟢',
    'open':     '🟠',
    'dead':     '🔴',
    'rift':     '🟣',
}
FIELD_EMOJI = {
    'ore':     '⛏️',
    'ice':     '🧊',
    'gas':     '☁️',
    'dark':    '🌑',
    'plasma':  '⚡',
    'quantum': '🔮',
}

# ── Slot calculations ─────────────────────────────────────────────────────────
def planet_slots(p):
    size  = p.get('size') or 0
    ptype = (p.get('planetType') or '').lower()
    return int(size / 10 * 0.3) if ptype == 'gas_giant' else int(size / 10)

def moon_slots(m):
    if m.get('buildingSlots') is not None:
        return int(m['buildingSlots'])
    return int((m.get('size') or 0) / 10)

# ── Formatting ────────────────────────────────────────────────────────────────
def fmt_type(t):
    t = (t or 'unknown').lower()
    return f"{PLANET_EMOJI.get(t, '❓')} {t.replace('_', ' ').title()}"

def fmt_zone(z):
    z = (z or '?').lower()
    return f"{ZONE_EMOJI.get(z, '❓')} {z.title()}"

def fmt_field(ft):
    ft = (ft or '?').lower()
    return f"{FIELD_EMOJI.get(ft, '🪨')} {ft.title()}"

def col_str(p):
    if not p.get('userId') and not p.get('colonizedAt'):
        return ''
    name = p.get('ownerName')
    tag  = p.get('ownerAllianceTag')
    tag_str = f' [{tag}]' if tag else ''
    return f'  [col: {name}{tag_str}]' if name else '  [col]'

def moon_col_str(m):
    if not m.get('userId') and not m.get('colonizedAt'):
        return ''
    name = m.get('ownerName')
    return f' ★{name}' if name else ' ★'

# ── System name parsing ───────────────────────────────────────────────────────
_SYS_RE = re.compile(r'^([A-Za-z]+)(\d+)-(\d+)$')

def parse_system_name(name):
    """'E47-19' -> ('E', 47, 19). Returns None for non-standard names."""
    if not name:
        return None
    m = _SYS_RE.match(name.strip())
    if not m:
        return None
    return m.group(1).upper(), int(m.group(2)), int(m.group(3))

def arm_letter_from_filter(arm_filter):
    if not arm_filter:
        return None
    af = arm_filter.strip().lower()
    return ARM_NAMES_LOWER.get(af) or af[0].upper()

def arm_full_name(letter):
    return ARM_LETTERS.get(letter.upper(), letter.upper())

# ── Argument parsing ──────────────────────────────────────────────────────────
def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('file')
    p.add_argument('--arm',             default=None)
    p.add_argument('--sector',          type=int,   default=None)
    p.add_argument('--type',            dest='ptype', default=None)
    p.add_argument('--zone',            default=None)
    p.add_argument('--pvp',             action='store_true')
    p.add_argument('--min-slots',       type=int,   default=0)
    p.add_argument('--colonized',       action='store_true')
    p.add_argument('--unaffiliated',    action='store_true')
    p.add_argument('--alliance',        default=None)
    p.add_argument('--player',          default=None)
    p.add_argument('--list-alliances',  action='store_true')
    p.add_argument('--field-type',      default=None)
    p.add_argument('--min-richness',    type=float, default=0.0)
    p.add_argument('--sort-slots',      action='store_true')
    p.add_argument('--top',             type=int,   default=25)
    args = p.parse_args()
    if args.sector is not None and not args.arm:
        p.error('--sector requires --arm  (e.g. --arm epsilon --sector 47)')
    return args

# ── Data loading ──────────────────────────────────────────────────────────────
def load(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)

def extract_data(raw):
    """
    Reads nl_dumper.py output (systems[] with nested planets/moons/asteroidFields).
    Returns (systems, meta).
    """
    if not (raw.get('systems') and isinstance(raw['systems'], list)
            and raw['systems'] and 'planets' in raw['systems'][0]):
        print('ERROR: Unrecognized format. Load a nexus-map-clean.json '
              'generated by nl_dumper.py.', file=sys.stderr)
        sys.exit(1)

    meta = {
        'capturedAt':         raw.get('meta', {}).get('capturedAt') or 'unknown',
        'systemCount':        raw.get('meta', {}).get('systemCount', 0),
        'planetCount':        raw.get('meta', {}).get('planetCount', 0),
        'moonCount':          raw.get('meta', {}).get('moonCount', 0),
        'asteroidFieldCount': raw.get('meta', {}).get('asteroidFieldCount', 0),
        'stationCount':       raw.get('meta', {}).get('stationCount', 0),
    }

    # Only full-visibility named systems
    systems = [s for s in raw['systems']
               if s.get('visibility') == 'full' and s.get('name')]

    return systems, meta

# ── Filtering ─────────────────────────────────────────────────────────────────
def system_arm_sector(s):
    parsed = parse_system_name(s.get('name', ''))
    if parsed:
        return parsed[0], parsed[1]
    return None, None

def system_passes(s, args):
    arm_letter, sector_num = system_arm_sector(s)
    target_arm = arm_letter_from_filter(args.arm)

    if target_arm and arm_letter != target_arm:
        return False
    if args.sector is not None and sector_num != args.sector:
        return False
    if args.pvp and (s.get('securityZone') or '').lower() == 'sentinel':
        return False
    if args.zone and (s.get('securityZone') or '').lower() != args.zone.lower():
        return False

    planets = s.get('planets') or []

    # Alliance filter
    if args.alliance:
        tag = args.alliance.upper()
        return any((p.get('ownerAllianceTag') or '').upper() == tag for p in planets)

    # Player filter
    if args.player:
        needle = args.player.lower()
        return any(needle in (p.get('ownerName') or '').lower() for p in planets)

    # Unaffiliated filter
    if args.unaffiliated:
        return any(p.get('userId') and not p.get('ownerAllianceTag') for p in planets)

    # Colonized filter
    if args.colonized:
        return any(p.get('userId') for p in planets)

    # Planet type / min slots
    if args.ptype or args.min_slots:
        planet_ok = any(
            (not args.ptype or (p.get('planetType') or '').lower() == args.ptype.lower())
            and planet_slots(p) >= args.min_slots
            for p in planets
        )
        if not planet_ok:
            # Still pass if asteroid field filter matches
            if not (args.field_type or args.min_richness):
                return False

    # Asteroid field filter
    if args.field_type or args.min_richness:
        fields = s.get('asteroidFields') or []
        field_ok = any(
            (not args.field_type or (af.get('fieldType') or '').lower() == args.field_type.lower())
            and (af.get('richness') or 0) >= args.min_richness
            for af in fields
        )
        if not field_ok:
            return False

    return True

# ── List alliances ────────────────────────────────────────────────────────────
def list_alliances(systems):
    counts = Counter(
        p.get('ownerAllianceTag')
        for s in systems
        for p in (s.get('planets') or [])
        if p.get('ownerAllianceTag')
    )
    lines = ['```']
    lines.append('╔══════════════════════════════════════════╗')
    lines.append('║   NEXUS LEGACY — ALLIANCE COLONY INDEX  ║')
    lines.append('╚══════════════════════════════════════════╝')
    lines.append(f'  {"Tag":<14}  Planets')
    lines.append(f'  {"─"*14}  {"─"*7}')
    for tag, count in counts.most_common():
        lines.append(f'  {tag:<14}  {count}')
    lines.append(f'\n  {len(counts)} alliances  |  {sum(counts.values())} tagged planets')
    lines.append('```')
    return '\n'.join(lines)

# ── Output builder ────────────────────────────────────────────────────────────
def build_output(systems, meta, args):
    qualifying = [s for s in systems if system_passes(s, args)]

    def sort_key(s):
        if args.sort_slots:
            best = max((planet_slots(p) for p in (s.get('planets') or [])), default=0)
            return (-best, s.get('name', ''))
        return s.get('name', '')

    qualifying.sort(key=sort_key)

    # Timestamp
    updated = meta.get('capturedAt', 'unknown')
    try:
        updated = datetime.fromisoformat(
            updated.replace('Z', '+00:00')
        ).strftime('%Y-%m-%d %H:%M UTC')
    except Exception:
        pass

    # Filter description
    filters = []
    if args.arm:          filters.append(f'arm={args.arm}')
    if args.sector:       filters.append(f'sector={args.sector}')
    if args.pvp:          filters.append('PvP zones only')
    if args.zone:         filters.append(f'zone={args.zone}')
    if args.ptype:        filters.append(f'type={args.ptype}')
    if args.min_slots:    filters.append(f'min-slots≥{args.min_slots}')
    if args.colonized:    filters.append('colonized only')
    if args.unaffiliated: filters.append('unaffiliated only')
    if args.alliance:     filters.append(f'alliance={args.alliance.upper()}')
    if args.player:       filters.append(f'player={args.player}')
    if args.field_type:   filters.append(f'field-type={args.field_type}')
    if args.min_richness: filters.append(f'min-richness≥{args.min_richness}')
    if args.sort_slots:   filters.append('sorted by slots')
    filter_str = ', '.join(filters) if filters else 'none'

    lines = []
    lines.append('```')
    lines.append('╔══════════════════════════════════════════╗')
    lines.append('║   NEXUS LEGACY — SCOUT DATABASE REPORT  ║')
    lines.append('╚══════════════════════════════════════════╝')
    lines.append(f'  Updated  : {updated}')
    lines.append(f'  Systems  : {meta["systemCount"]:,} total | {len(qualifying)} match filters')
    lines.append(f'  Planets  : {meta["planetCount"]:,}')
    lines.append(f'  Moons    : {meta["moonCount"]:,}')
    lines.append(f'  Fields   : {meta["asteroidFieldCount"]:,}')
    lines.append(f'  Stations : {meta["stationCount"]:,}')
    lines.append(f'  Filters  : {filter_str}')
    lines.append('')

    shown = 0
    for s in qualifying:
        if shown >= args.top:
            remaining = len(qualifying) - shown
            lines.append(f'  ... and {remaining} more systems (use --top to increase)')
            break

        planets  = sorted(s.get('planets') or [],
                          key=lambda p: p.get('position') or 0)
        fields   = sorted(s.get('asteroidFields') or [],
                          key=lambda f: f.get('richness') or 0, reverse=True)
        stations = s.get('stations') or []

        zone = fmt_zone(s.get('securityZone'))
        star = s.get('starType') or '?'

        parsed = parse_system_name(s.get('name', ''))
        if parsed:
            arm_letter, sector_num, sys_num = parsed
            header_loc = (f'{arm_full_name(arm_letter)} Arm - '
                          f'Sector {sector_num}  |  System {sys_num}')
        else:
            header_loc = s.get('name', f'System {s["id"]}')

        # Station line if present
        st_str = ''
        if stations:
            st = stations[0]
            owned = st.get('ownerAllianceTag')
            capturing = st.get('capturingAllianceTag')
            shield_pct = (
                round(st['shieldHp'] / st['shieldMaxHp'] * 100)
                if st.get('shieldMaxHp') else 100
            )
            st_parts = [f'🏛 {st.get("name", "Station")}']
            st_parts.append(f'🛡{shield_pct}%')
            if owned:
                st_parts.append(f'⚑{owned}')
            else:
                st_parts.append('neutral')
            if capturing:
                st_parts.append(f'⚔{capturing} capturing')
            st_str = '  ' + '  '.join(st_parts)

        lines.append(f'┌─ {header_loc}  |  {zone}  |  ★ {star}{st_str}')

        for p in planets:
            slots = planet_slots(p)
            ptype = fmt_type(p.get('planetType'))
            pos   = p.get('position', '?')
            cstr  = col_str(p)

            # Planet passes filter?
            p_passes = True
            if args.ptype and (p.get('planetType') or '').lower() != args.ptype.lower():
                p_passes = False
            if args.min_slots and slots < args.min_slots:
                p_passes = False
            if args.colonized and not p.get('userId'):
                p_passes = False
            if args.alliance:
                if (p.get('ownerAllianceTag') or '').upper() != args.alliance.upper():
                    p_passes = False
            if args.player:
                if args.player.lower() not in (p.get('ownerName') or '').lower():
                    p_passes = False
            if args.unaffiliated:
                if not (p.get('userId') and not p.get('ownerAllianceTag')):
                    p_passes = False

            moons = sorted(p.get('moons') or [],
                           key=lambda m: -moon_slots(m))
            moon_str = ''
            if moons:
                parts = []
                for m in moons:
                    msl   = moon_slots(m)
                    mtype = m.get('moonType') or '?'
                    mcol  = moon_col_str(m)
                    parts.append(f'{mtype} {msl}sl{mcol}')
                moon_str = '  🌙 [' + ', '.join(parts) + ']'

            dim  = '│' if p_passes else '·'
            line = f'{dim}  P{pos}  {ptype:22s}  {slots:>2}sl{cstr}{moon_str}'
            lines.append(line.rstrip())

        for f in fields:
            ft = (f.get('fieldType') or '').lower()
            if args.field_type and ft != args.field_type.lower():
                continue
            if (f.get('richness') or 0) < args.min_richness:
                continue
            remaining = f.get('remainingResources')
            rem_str   = f'  remaining {remaining:,}' if remaining is not None else ''
            ctrl      = f.get('controllerName')
            ctrl_str  = f'  ⚑{ctrl}' if ctrl else ''
            lines.append(
                f'│  {fmt_field(ft):16s}  '
                f'richness {f.get("richness") or 0:.2f}'
                f'{rem_str}{ctrl_str}'
            )

        lines.append('')
        shown += 1

    lines.append('```')
    return '\n'.join(lines)

# ── Entry point ───────────────────────────────────────────────────────────────
def main():
    args = parse_args()
    raw  = load(args.file)
    systems, meta = extract_data(raw)

    if args.list_alliances:
        print(list_alliances(systems))
        return

    output = build_output(systems, meta, args)
    print(output)

    out_path = args.file.rsplit('.', 1)[0] + '_discord.txt'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(output)
    print(f'\n[Saved to {out_path}]', file=sys.stderr)

if __name__ == '__main__':
    main()
